### ISSUE TITLE
Create firefox extension

### ISSUE THREAD

**Issue by andykog** [andykog/mobx-devtools#6]

**Comment by andykog** [comment]
Firefox extension is made, but there ase some problems with accepting it on addons.mozilla.org

**Comment by andykog** [comment]
Done https://addons.mozilla.org/ru/firefox/addon/mobx-devtools

**Comment by arminghm** [comment]
Hi
mobx-dev-tools is checked in settings, but it doesn't appear!
I even restart firefox but still don't see Mobx in dev-tools
